version: '3'

networks:
  app:

services:

  todotests:
    image: todotests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    networks:
      - app
    restart: always

  todofront:
    image: todofrontend
    depends_on:
      - todoback
    expose:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - app
    restart: always

  todoback:
    image: todobackend
    expose:
      - 3001:3001
    networks:
      - app
    restart: always
